## 第一章第一节  简介

In [4]:
import tensorflow as tf
import pandas as pd
import numpy as np
from gensim.models import Word2Vec
import jieba  # 中文分词库，百度员工开发
import matplotlib.pyplot as plt 
import time
# 查询系统可用的 GPU
physical_devices = tf.config.experimental.list_physical_devices('GPU')
print(physical_devices)
# 确保有可用的 GPU 如果没有, 则会报错
assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
# 设置参数,该段务必在运行jupyter的第一段代码执行，否则会无法初始化成功
# 仅在需要时申请显存空间（程序初始运行时消耗很少的显存，随着程序的运行而动态申请显存）
tf.config.experimental.set_memory_growth(physical_devices[0], True)

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


#### tensorflow2.0相比较1.0在API接口上调用更加易用，将Keras收购后完全融入为新的子接口做深度学习调用tf.keras

In [19]:
# 通过tensorflow计算常量示例
a = tf.constant(3,dtype='int16')
b = tf.constant(5,dtype='int16')
c = a*b
print(c)

tf.Tensor(15, shape=(), dtype=int16)


In [22]:
a = tf.constant(3,shape=(2,3))
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [13]:
print(tf.constant(5) * tf.constant(4))

tf.Tensor(20, shape=(), dtype=int32)


#### tensorflow装饰器调用展示

In [8]:
@tf.function
def simple_nn_layer(x,y):
    return tf.nn.relu(tf.matmul(x,y)) # 矩阵乘法，而不是元素乘法

x = tf.random.uniform(shape=(3,3),maxval=100,dtype = tf.int32) # 生成一个3*3的随机实数2D张量
y = tf.random.uniform(shape=(3,3),maxval=3,dtype = tf.int32)

In [9]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[35,  6, 97],
       [28, 21, 81],
       [ 8, 16, 67]], dtype=int32)>

In [10]:
y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 2, 1],
       [1, 2, 0]], dtype=int32)>

In [11]:
simple_nn_layer(x,y) # 通过装饰器调用图算法

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 97, 206,   6],
       [ 81, 204,  21],
       [ 67, 166,  16]], dtype=int32)>

In [14]:
x[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([35,  6, 97], dtype=int32)>

In [13]:
tf.print(sum(x[0] * y[:,0]))
tf.print(sum(x[0] * y[:,1]))
tf.print(sum(x[0] * y[:,2]))

97
206
6


#### 常用tf接口

![常用tf接口](./markdown_pics/tf常用接口.jpg)

### 一、TensorFlow低阶API

![常用tf接口](./markdown_pics/tf低阶API.jpg)

In [15]:
# 低阶API举例
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])

# 标量计算 a+b
tf.math.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>

In [17]:
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
# 标量计算 a-b
tf.math.subtract(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]], dtype=int32)>

In [9]:
# 标量计算 a*b 乘法
tf.math.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [10]:
# 标量计算 a/b 除法
tf.math.divide(a,b)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])>

In [11]:
# 向量计算
a = tf.range(1,100)

In [12]:
a

<tf.Tensor: shape=(99,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int32)>

In [13]:
tf.print(tf.reduce_sum(a))

4950


In [14]:
tf.print(tf.reduce_mean(a))

50


In [15]:
tf.print(tf.reduce_max(a))

99


In [16]:
tf.print(tf.reduce_min(a))


1


In [18]:
tf.print(tf.reduce_prod(a)) #此函数计算一个张量的各个维度上元素的乘积

0


### 二、TensorFlow中阶API

![常用tf接口](./markdown_pics/tf中阶API.jpg)


In [23]:
# 中阶
a = tf.random.uniform(shape=(10,5),minval=0,maxval = 10) #生成10乘以5的均匀分布的张量，均匀分布会定义一个最大值和最小值

In [24]:
a

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.17774701, 2.9730237 , 6.28574   , 3.551135  , 7.1986284 ],
       [8.255257  , 7.9624367 , 6.452936  , 7.8144827 , 3.1595635 ],
       [6.4324865 , 3.4416294 , 8.746914  , 6.3547287 , 1.7798173 ],
       [0.30650258, 3.6757684 , 6.609447  , 5.704936  , 7.5399947 ],
       [5.03374   , 9.812571  , 1.6079056 , 4.5578146 , 1.7115128 ],
       [8.427334  , 4.987854  , 4.3054047 , 6.791686  , 6.7254043 ],
       [4.7570314 , 6.6888785 , 9.703931  , 4.2203655 , 6.257417  ],
       [5.5932426 , 1.81211   , 2.5132215 , 1.3635194 , 0.23848176],
       [2.7033746 , 0.7865381 , 8.2957945 , 8.912367  , 5.2475014 ],
       [3.4562147 , 7.5318966 , 7.8864    , 3.1740856 , 8.271439  ]],
      dtype=float32)>

In [25]:
tf.nn.softmax(a)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[6.18906226e-04, 1.01297349e-02, 2.78158635e-01, 1.80579629e-02,
        6.93034768e-01],
       [3.90513122e-01, 2.91383892e-01, 6.44017681e-02, 2.51310080e-01,
        2.39113579e-03],
       [8.26166645e-02, 4.15102066e-03, 8.36008489e-01, 7.64359832e-02,
        7.87842087e-04],
       [4.58222668e-04, 1.33146588e-02, 2.50270963e-01, 1.01294607e-01,
        6.34661555e-01],
       [8.28809012e-03, 9.85993862e-01, 2.69546319e-04, 5.14947157e-03,
        2.98971252e-04],
       [7.01531887e-01, 2.25061029e-02, 1.13740815e-02, 1.36676744e-01,
        1.27911255e-01],
       [6.50583068e-03, 4.49048504e-02, 9.15617049e-01, 3.80392303e-03,
        2.91683618e-02],
       [9.19086277e-01, 2.09522769e-02, 4.22396287e-02, 1.33786080e-02,
        4.34323261e-03],
       [1.28293422e-03, 1.88683000e-04, 3.44319284e-01, 6.37874663e-01,
        1.63344499e-02],
       [3.73181445e-03, 2.19768837e-01, 3.13274533e-01, 2.81444564e-03,
      

In [36]:
 a = tf.random.uniform(shape=(10,5),minval = -0.5, maxval = 0.5)

In [42]:
b = tf.keras.layers.Dense(10)(a)
b.shape

TensorShape([10, 10])

In [43]:
a = tf.random.uniform(shape=(10,5),minval = -0.5,maxval = 0.5)
tf.print('做线性变换前的维度\n',a.shape)
b = tf.keras.layers.Dense(10)(a)
tf.print('做线性变换后的维度\n',b.shape)
b = tf.nn.softmax(b)
b

做线性变换前的维度
 TensorShape([10, 5])
做线性变换后的维度
 TensorShape([10, 10])


<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.1970199 , 0.06478176, 0.08340064, 0.05789879, 0.05120848,
        0.07919518, 0.12206888, 0.10725715, 0.13625334, 0.10091584],
       [0.1970199 , 0.06478176, 0.08340064, 0.05789879, 0.05120848,
        0.07919518, 0.12206888, 0.10725715, 0.13625334, 0.10091584],
       [0.1970199 , 0.06478176, 0.08340064, 0.05789879, 0.05120848,
        0.07919518, 0.12206888, 0.10725715, 0.13625334, 0.10091584],
       [0.1970199 , 0.06478176, 0.08340064, 0.05789879, 0.05120848,
        0.07919518, 0.12206888, 0.10725715, 0.13625334, 0.10091584],
       [0.1970199 , 0.06478176, 0.08340064, 0.05789879, 0.05120848,
        0.07919518, 0.12206888, 0.10725715, 0.13625334, 0.10091584],
       [0.1970199 , 0.06478176, 0.08340064, 0.05789879, 0.05120848,
        0.07919518, 0.12206888, 0.10725715, 0.13625334, 0.10091584],
       [0.1970199 , 0.06478176, 0.08340064, 0.05789879, 0.05120848,
        0.07919518, 0.12206888, 0.10725715, 0.13625334, 0.10

In [30]:
a = tf.random.uniform(shape=(10,100,50),minval = -0.5,maxval = -0.5)
a = tf.keras.layers.LSTM(100)(a)
b = tf.keras.layers.Dense(10)(a)
b = tf.nn.softmax(b)
b

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.1415823 , 0.10353278, 0.09819841, 0.08567477, 0.06916812,
        0.13720214, 0.11492527, 0.07812237, 0.08605745, 0.08553635],
       [0.1415823 , 0.10353278, 0.09819841, 0.08567477, 0.06916812,
        0.13720214, 0.11492527, 0.07812237, 0.08605745, 0.08553635],
       [0.1415823 , 0.10353278, 0.09819841, 0.08567477, 0.06916812,
        0.13720214, 0.11492527, 0.07812237, 0.08605745, 0.08553635],
       [0.1415823 , 0.10353278, 0.09819841, 0.08567477, 0.06916812,
        0.13720214, 0.11492527, 0.07812237, 0.08605745, 0.08553635],
       [0.1415823 , 0.10353278, 0.09819841, 0.08567477, 0.06916812,
        0.13720214, 0.11492527, 0.07812237, 0.08605745, 0.08553635],
       [0.1415823 , 0.10353278, 0.09819841, 0.08567477, 0.06916812,
        0.13720214, 0.11492527, 0.07812237, 0.08605745, 0.08553635],
       [0.1415823 , 0.10353278, 0.09819841, 0.08567477, 0.06916812,
        0.13720214, 0.11492527, 0.07812237, 0.08605745, 0.08

### 三、TensorFlow高阶API

![常用tf接口](./markdown_pics/tf高阶API.jpg)

In [52]:
# 高阶API应用
X = tf.random.uniform(shape=(10,100,50),minval = -0.5,maxval = 0.5)

In [53]:
y = tf.random.categorical(tf.random.uniform(shape=(10,3),minval = -0.5,maxval = 0.5),2)

In [46]:
model = tf.keras.models.Sequential()

In [47]:
model.add(tf.keras.layers.LSTM(100,input_shape = (100,50)))
model.add(tf.keras.layers.Dense(10))
model.add(tf.keras.layers.Dense(2,activation = 'softmax'))

In [48]:
model.compile(optimizer='adam',loss = 'categorical_crossentropy',metrics=['accuracy'])

In [49]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 100)               60400     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1010      
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 22        
Total params: 61,432
Trainable params: 61,432
Non-trainable params: 0
_________________________________________________________________


In [50]:
model.fit(X,y)

1/1 [==============================] - 0s 4ms/step - loss: 1.5779 - accuracy: 0.3000


![常用tf接口](./markdown_pics/tfAPI总结.jpg)

## 本章完结

#### 1.待掌握softmax函数的原理
#### 2.tf.keras.layers.Dense 的具体原理

In [34]:
inputs = np.array([[1., 2., 3., 4., 5.]])

# 这里表示的w
kernel =  np.array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]
 , [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]
 , [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]
 , [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]
 , [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

b =  np.array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
print(inputs.shape, kernel.shape, b.shape)

(1, 5) (5, 10) (10,)


In [37]:
tf.matmul(inputs,kernel)

<tf.Tensor: shape=(1, 10), dtype=float64, numpy=array([[ 15.,  30.,  45.,  60.,  75.,  90., 105., 120., 135., 150.]])>

In [39]:
tf.matmul(inputs,kernel) + b

<tf.Tensor: shape=(1, 10), dtype=float64, numpy=array([[ 15.,  31.,  47.,  63.,  79.,  95., 111., 127., 143., 159.]])>

In [13]:
tf.print(tf.reduce_max(tf.constant(1,3)))

1


In [17]:
print(tf.constant(1,2))

tf.Tensor(1.0, shape=(), dtype=float64)


In [2]:
help(tf.reduce_max)

Help on function reduce_max in module tensorflow.python.ops.math_ops:

reduce_max(input_tensor, axis=None, keepdims=False, name=None)
    Computes the maximum of elements across dimensions of a tensor.
    
    Reduces `input_tensor` along the dimensions given in `axis`.
    Unless `keepdims` is true, the rank of the tensor is reduced by 1 for each
    entry in `axis`. If `keepdims` is true, the reduced dimensions
    are retained with length 1.
    
    If `axis` is None, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    Usage example:
    
    >>> x = tf.constant([5, 1, 2, 4])
    >>> print(tf.reduce_max(x))
    tf.Tensor(5, shape=(), dtype=int32)
    >>> x = tf.constant([-5, -1, -2, -4])
    >>> print(tf.reduce_max(x))
    tf.Tensor(-1, shape=(), dtype=int32)
    >>> x = tf.constant([4, float('nan')])
    >>> print(tf.reduce_max(x))
    tf.Tensor(4.0, shape=(), dtype=float32)
    >>> x = tf.constant([float('nan'), float('nan')])
    >>> print(t

##### 对Dense层做最基础的测试试图理解内部

In [6]:
help(tf.keras.layers.Dense(units=2))

re constants defined in the class
 |          `tf.VariableAggregation`.
 |        **kwargs: Additional keyword arguments. Accepted values are `getter`,
 |          `collections`, `experimental_autocast` and `caching_device`.
 |      
 |      Returns:
 |        The created variable. Usually either a `Variable` or `ResourceVariable`
 |        instance. If `partitioner` is not `None`, a `PartitionedVariable`
 |        instance is returned.
 |      
 |      Raises:
 |        RuntimeError: If called with partitioned variable regularization and
 |          eager execution is enabled.
 |        ValueError: When giving unsupported dtype and no initializer or when
 |          trainable has been set to True with synchronization set as `ON_READ`.
 |  
 |  apply(self, inputs, *args, **kwargs)
 |      Deprecated, do NOT use! (deprecated)
 |      
 |      Warning: THIS FUNCTION IS DEPRECATED. It will be removed in a future version.
 |      Instructions for updating:
 |      Please use `layer.__call_

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from gensim.models import Word2Vec
import jieba  # 中文分词库，百度员工开发
import matplotlib.pyplot as plt 
import time
# # 查询系统可用的 GPU
# physical_devices = tf.config.experimental.list_physical_devices('GPU')
# # 确保有可用的 GPU 如果没有, 则会报错
# assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
# # 设置参数,该段务必在运行jupyter的第一段代码执行，否则会无法初始化成功
# # 仅在需要时申请显存空间（程序初始运行时消耗很少的显存，随着程序的运行而动态申请显存）
# tf.config.experimental.set_memory_growth(physical_devices[0], True)

In [9]:
X = np.array([[1,2],[2,2]])
print('X',X)
y = np.array([1,0])
y = tf.one_hot(y,2)
tf.print('y',y)
model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Dense(units= 2,input_shape = (2,)))
# units= 2 该层的神经元个数
model.add(tf.keras.layers.Dense(units= 2, input_shape = (2,) ,activation = 'softmax'))

# 使用随机梯度下降作为优化器 、交叉熵损失函数、 准确率评估
model.compile(optimizer='sgd',loss = 'categorical_crossentropy',metrics=['accuracy'])
model.summary()
model.fit(X,y)

X [[1 2]
 [2 2]]
y [[0 1]
 [1 0]]
Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 2)                 6         
Total params: 6
Trainable params: 6
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 2ms/step - loss: 0.7530 - accuracy: 0.5000


In [12]:
# 此处着重还原Dense的处理过程

# 随机初始化 w、b
w = np.array([[0.1,0.3],[0.4,0.7]])
b = np.array([1,2])

c = np.dot(w, X) + b

In [14]:
# 将结果做softmax转换
tf.nn.softmax(c)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.24973989, 0.75026011],
       [0.19781611, 0.80218389]])>

In [15]:
# 生成预测结果
pred = [[0,1],[0,1]]

In [ ]:
# 真实结果
y = [[0,1],[1,0]]

In [ ]:
# 准确率 0.5

##### 手写一个SoftMax计算公式

In [50]:
import numpy as np 
def softMax(Trans_array:list):
    if len(Trans_array) == 0:
        return Trans_array
    sum_i = 0
    for i in range(len(Trans_array)):
        Trans_array[i]  = np.exp(Trans_array[i])
        sum_i += Trans_array[i]
    for log_i in range(len(Trans_array)):
        Trans_array[log_i] = round(Trans_array[log_i]/sum_i,4)
    return Trans_array, round(sum(Trans_array),2)

In [51]:
softMax([2,3,5])

([0.042, 0.1142, 0.8438], 1.0)

In [65]:
# 如果使用对数
import numpy as np 
def softMax(Trans_array:list):
    if len(Trans_array) == 0:
        return Trans_array
    sum_i = 0
    for i in range(len(Trans_array)):
        Trans_array[i]  = np.log(Trans_array[i])
        sum_i += Trans_array[i]
    for log_i in range(len(Trans_array)):
        Trans_array[log_i] = round(Trans_array[log_i]/sum_i,4)
    return Trans_array, round(sum(Trans_array),2)

In [66]:
softMax([2,3,5])

([0.2038, 0.323, 0.4732], 1.0)

In [67]:
scores = np.array([123, 456, 789])
scores -= np.max(scores)

In [68]:
scores

array([-666, -333,    0])

In [69]:
z = tf.random.normal([2,10])
z

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-1.5390596 ,  0.5894602 , -0.55105644, -0.3392847 ,  0.5044844 ,
         1.0958196 , -0.30700386,  0.12144363, -2.0147839 ,  0.55208945],
       [ 0.31052962, -1.2160761 ,  1.764273  ,  0.13621946,  2.264149  ,
         0.8540781 ,  0.24092601, -0.06370308, -2.3819096 , -0.2245071 ]],
      dtype=float32)>

In [70]:
z = tf.random.normal([2, 10]) # 构造2个样本的10类别输出的输出值
y = tf.constant([1, 3]) # 两个样本的真实样本标签是1和3
y_true = tf.one_hot(y, depth = 10) # 构造onehot编码

In [71]:
z

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 1.0583026 ,  0.1122171 ,  0.63292325,  1.0119021 ,  0.8550314 ,
        -1.0603844 ,  0.5451556 ,  1.5006305 , -0.13813645, -0.66283834],
       [ 0.65085083,  0.1896415 , -0.7920322 , -0.7588749 , -0.44227013,
        -0.32016006, -0.12084924,  1.1455139 , -0.1418101 ,  0.5171825 ]],
      dtype=float32)>

In [72]:
y_true

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [73]:
loss1 = tf.keras.losses.categorical_crossentropy(y_true, z, from_logits = True)
loss1 = tf.reduce_mean(loss1)

In [74]:
loss1

<tf.Tensor: shape=(), dtype=float32, numpy=3.035721>

In [75]:
y_pred = tf.nn.softmax(z)

In [76]:
y_pred

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0.15223597, 0.0591068 , 0.09948952, 0.1453335 , 0.1242332 ,
        0.01829714, 0.09112978, 0.23692876, 0.04601616, 0.02722922],
       [0.15988393, 0.10081013, 0.03777189, 0.0390453 , 0.05358811,
        0.06054805, 0.0739026 , 0.26220095, 0.07236966, 0.1398793 ]],
      dtype=float32)>

In [77]:
# 输出层经过Softmax激活函数,因此将from_logits设置为True
loss2 = tf.keras.losses.categorical_crossentropy(y_true, y_pred, from_logits = False)
loss2 = tf.reduce_mean(loss2)
print(loss2) # tf.Tensor(2.668019, shape=(), dtype=float32)

tf.Tensor(3.0357208, shape=(), dtype=float32)
