In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import time

#### 1.对list的append数组和np.stack功能进行理解

In [5]:
h = []
i = np.array([1,2])
j = np.array([3,4])
h.append(i)
print('第一次添加后结果\n',h)
h.append(j)
print('第二次添加后结果\n',h)
h = np.array(h)
print('转换后结果\n',h)
h.shape
np.stack(h, axis = 0)

第一次添加后结果
 [array([1, 2])]
第二次添加后结果
 [array([1, 2]), array([3, 4])]
转换后结果
 [[1 2]
 [3 4]]


array([[1, 2],
       [3, 4]])

#### 2.对np.dot的矩阵相乘的各种场景进行掌握
- **特别注意的一点是，矩阵的这种相乘能够起到降维的效果**

In [6]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
c = np.array([[1, 0], [0, 1],[3,3]])
d = np.array([[1, 0, 3], [0, 1, 5]])
e = np.array([1, 0, 3])
f = np.array([[1, 0, 3]])
g = np.array([[1], [0], [3]])
h = np.zeros((3,))

In [8]:
print('注意区分e和f的形状不同')
print(e.shape,f.shape)

注意区分e和f的形状不同
(3,) (1, 3)


In [9]:
print('矩阵相乘，要求a矩阵的列数必须等于b矩阵的行数，新生成的矩阵大小为(a的行数，b的列数）')
np.dot(a, b)

矩阵相乘，要求a矩阵的列数必须等于b矩阵的行数，新生成的矩阵大小为(a的行数，b的列数）


array([[4, 1],
       [2, 2]])

In [11]:
# 不服从该规则将会报错
np.dot(a, c)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [12]:
np.dot(a,d)

array([[1, 0, 3],
       [0, 1, 5]])

In [13]:
np.dot(c,d)

array([[ 1,  0,  3],
       [ 0,  1,  5],
       [ 3,  3, 24]])

In [14]:
np.dot(d,c)

array([[10,  9],
       [15, 16]])

In [15]:
np.dot(c, e)

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [19]:
print('一个2D张量和一个1D张量相乘仍然遵守该规则')
np.dot(d, e)

print('d的形状',d.shape,'\te的形状',e.shape)
print('相乘后的结果',np.dot(d, e).shape)

一个2D张量和一个1D张量相乘仍然遵守该规则
d的形状 (2, 3) 	e的形状 (3,)
相乘后的结果 (2,)


In [20]:
np.dot(d, f)

ValueError: shapes (2,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [24]:
print(np.dot(d, g),'\n')
print('d的形状',d.shape,'\tg的形状',g.shape)
print('相乘后的结果',np.dot(d, g).shape)

[[10]
 [15]] 

d的形状 (2, 3) 	e的形状 (3, 1)
相乘后的结果 (2, 1)


In [26]:
# h 是一个全零向量
print(np.dot(d, h))

print('d的形状',d.shape,'\th的形状',h.shape)

[0. 0.]
d的形状 (2, 3) 	h的形状 (3,)


In [28]:
print(e)
print(h)
print('相加的结果',e+h)

[1 0 3]
[0. 0. 0.]
相加的结果 [1. 0. 3.]


In [43]:
# 矩阵乘以一个数
a * 0.88

array([[0.88, 0.  ],
       [0.  , 0.88]])

#### 3.np.tanh的理解：对张量的每个元素都执行(-1,1)区间的值转换

In [30]:
print(e)
print(np.tanh(e))

[1 0 3]
[0.76159416 0.         0.99505475]


#### 4.一个简单的循环神经网络结构

In [31]:
timesteps = 100 # 定义输入序列的时间步数

input_features = 32 # 输入空间的特征维度

output_features = 64 # 输出空间的特征维度

In [32]:
inputs = np.random.random((timesteps, input_features)) #输入数据示例

In [33]:
inputs.shape

(100, 32)

In [34]:
inputs[0]

array([7.76540238e-01, 6.03832627e-01, 5.57550213e-01, 1.18614793e-01,
       3.36323764e-02, 2.10216296e-01, 7.62642330e-02, 4.11604751e-04,
       3.91109452e-01, 3.87863468e-01, 7.04299231e-01, 8.81656938e-01,
       7.94264455e-01, 3.47134170e-01, 4.64626636e-01, 8.49172072e-01,
       2.81441461e-01, 1.89813652e-01, 4.79152566e-01, 8.82966069e-01,
       7.61673264e-01, 4.62764820e-01, 4.93057672e-01, 6.29697345e-01,
       2.69109300e-01, 5.82154651e-01, 6.70245962e-02, 9.29995278e-01,
       3.73652740e-01, 7.16194441e-01, 3.64521672e-01, 4.84751142e-01])

In [35]:
state_t = np.zeros((output_features,)) # 初始状态是一个全零向量

In [36]:
state_t.shape

(64,)

In [37]:
# 创建随机的权重矩阵
W = np.random.random((output_features,input_features))
U = np.random.random((output_features, output_features))
b = np.random.random((output_features,))

In [38]:
# 对每一个输入样本，输出的结果是  输入数据和当前时刻的上一个时刻的状态
successive_outputs = []

for input_t in inputs:
    output_t = np.tanh(np.dot(W, input_t) + np.dot(U, state_t) + b) 

    successive_outputs.append(output_t)

    state_t = output_t

In [39]:
final_output_sequence = np.stack(successive_outputs, axis = 0)

In [40]:
final_output_sequence.shape

(100, 64)

##### 总结步骤

In [41]:
print(W.shape, inputs[0].shape)
print('np.dot(W, input_t) 的结果是',np.dot(W, inputs[0]).shape)

(64, 32) (32,)
np.dot(W, input_t) 的结果是 (64,)


In [42]:
print(U.shape,state_t.shape)
print('np.dot(U, state_t) 的结果是一个全零向量，形状为',np.dot(U, state_t).shape)

(64, 64) (64,)
np.dot(U, state_t) 的结果是一个全零向量，形状为 (64,)
